apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-1
spec:
  containers:
  - name: gpu-container
    image: tovitu/seg_test:latest
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "1"
        memory: "16Gi"
      limits:
        cpu: "8"
        memory: "32Gi"
        nvidia.com/gpu: 1
    env:
      - name: "ID"
        value: "${ID}"
    volumeMounts:
      - name: "prp-s3-credentials"
        mountPath: "/root/.aws/credentials"
        subPath: "credentials"

  volumes:
    - name: prp-s3-credentials
      secret:
        secretName: prp-s3-credentials
